spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_management_system
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION_TIME:36000000}
